cider: 24
dns: 172.25.0.2
firewalls:
- http
- https
- ntp
gateway: 172.25.2.1
hostname: control
ip: 172.25.2.118
packages:
- httpd
- php
- chrony
services:
- httpd
- chrony
users:
- comment: WebAdminUser
  name: webadmin
- comment: ContentUPLoadUser
  name: upadmin
